services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build: .
    environment:
      - RUST_LOG=info
      # - AUTH_SERVER_URL=https://auth.sjallabong.eu
      - AUTH_ENV=production
      - DATABASE_URL=postgresql://auth_user:auth_password@db:5432/auth
    ports:
      - "3001:3001" # debug
    expose:
      - "3001"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
